name: Release

on:
  workflow_dispatch:
  push:

jobs:
  build_release_windows:
    name: "LLVM Windows"
    runs-on: windows-latest
    env:
      LLVM_INSTALL_PATH: C:/llvm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          lfs: true
          fetch-depth: 1

      - name: Set LLVM version
        shell: bash
        run: echo "LLVM_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install Ninja Generator
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.0

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile & Install LLVM
        shell: bash
        run: |
          ls
          mkdir build && cd build
          ls
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${{ env.LLVM_INSTALL_PATH }} \
            -DLLVM_ENABLE_PROJECTS=llvm;clang;lld;lldb \
            -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON \
            -DLLVM_ENABLE_TERMINFO=OFF \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_DOCS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_GO_TESTS=OFF \
            -DLLVM_INCLUDE_RUNTIMES=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_UTILS=ON \
            -DLLVM_USE_CRT_RELEASE=MT \
            ../llvm
          ls ../llvm
          ninja install
          copy lib/opt.lib ${{ env.LLVM_INSTALL_PATH }}/lib
          copy lib/lld.lib ${{ env.LLVM_INSTALL_PATH }}/lib

      - name: Create Archive
        run: 7z a -t7z llvm-lld-${{ env.LLVM_VERSION }}-windows-x86_64.7z ${{ env.LLVM_INSTALL_PATH }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LLVM_VERSION }}
          name: ${{ github.event.head_commit.message }}-${{ env.LLVM_VERSION }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: llvm-lld-${{ env.LLVM_VERSION }}-windows-x86_64.7z
